version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library_system_development
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "bundle exec rails tailwindcss:build && bin/vite build --clear --mode=development && bundle exec rails s -b 0.0.0.0 -p 3000"
    volumes:
      - ./app:/app/app
      - ./config:/app/config
      - ./db:/app/db
      - ./lib:/app/lib
      - ./public:/app/public
      - ./tmp:/app/tmp
      - ./log:/app/log
      - ./storage:/app/storage
      - ./Gemfile:/app/Gemfile
      - ./Gemfile.lock:/app/Gemfile.lock
      - ./Rakefile:/app/Rakefile
      - ./config.ru:/app/config.ru
      - ./README.md:/app/README.md
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/library_system_development
