default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] || "postgres://postgres:password@localhost:5432/library_system_development" %>

development:
  <<: *default
  database: library_system_development

test:
  <<: *default
  database: library_system_test

production:
  <<: *default
  database: library_system_production
